name: Execute Ping CI

on: [pull_request]

jobs:
  run-ci:
    name: Run AlgoPing CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10.8

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3

      - name: Install python dependencies
        run: poetry install

      - uses: pre-commit/action@v3.0.0
        name: "Linters and formatters check"
        with:
          extra_args: --all-files --show-diff-on-failure
